
import type { DefineComponent, SlotsType } from 'vue'
type IslandComponent<T extends DefineComponent> = T & DefineComponent<{}, {refresh: () => Promise<void>}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, SlotsType<{ fallback: { error: unknown } }>>
interface _GlobalComponents {
      'AboutOne': typeof import("../components/about/AboutOne.vue")['default']
    'AboutResume': typeof import("../components/about/AboutResume.vue")['default']
    'BlogList': typeof import("../components/blog/BlogList.vue")['default']
    'BlogOne': typeof import("../components/blog/BlogOne.vue")['default']
    'BlogSwiper': typeof import("../components/blog/BlogSwiper.vue")['default']
    'BlogPostComments': typeof import("../components/blog/PostComments.vue")['default']
    'BlogPostCommentsForm': typeof import("../components/blog/PostCommentsForm.vue")['default']
    'BlogPostData': typeof import("../components/blog/PostData.vue")['default']
    'BlogPostItem': typeof import("../components/blog/PostItem.vue")['default']
    'BlogPostPagination': typeof import("../components/blog/PostPagination.vue")['default']
    'BoxImage': typeof import("../components/box-image/BoxImage.vue")['default']
    'BoxInfo': typeof import("../components/box-info/BoxInfo.vue")['default']
    'BoxInfoFull': typeof import("../components/box-info/BoxInfoFull.vue")['default']
    'BoxInfoItem': typeof import("../components/box-info/BoxInfoItem.vue")['default']
    'BoxInfoList': typeof import("../components/box-info/BoxInfoList.vue")['default']
    'BoxInfoRight': typeof import("../components/box-info/BoxInfoRight.vue")['default']
    'Brand': typeof import("../components/brand/Brand.vue")['default']
    'BrandHorizontal': typeof import("../components/brand/BrandHorizontal.vue")['default']
    'BrandOne': typeof import("../components/brand/BrandOne.vue")['default']
    'BrandTwo': typeof import("../components/brand/BrandTwo.vue")['default']
    'ContactForm': typeof import("../components/contact/ContactForm.vue")['default']
    'ContactFormSmall': typeof import("../components/contact/ContactFormSmall.vue")['default']
    'ContactDsnMap': typeof import("../components/contact/DsnMap.vue")['default']
    'ExperienceItem': typeof import("../components/experience/ExperienceItem.vue")['default']
    'ExperienceList': typeof import("../components/experience/ExperienceList.vue")['default']
    'FooterDsnFooter': typeof import("../components/footer/DsnFooter.vue")['default']
    'HeaderResume': typeof import("../components/header/HeaderResume.vue")['default']
    'HelperScrollSmooth': typeof import("../components/helper/ScrollSmooth.vue")['default']
    'ImagesImagePopup': typeof import("../components/images/ImagePopup.vue")['default']
    'ImagesParallaxImage': typeof import("../components/images/ParallaxImage.vue")['default']
    'ImagesParallaxImageTwo': typeof import("../components/images/ParallaxImageTwo.vue")['default']
    'ImagesScrollImages': typeof import("../components/images/ScrollImages.vue")['default']
    'ImagesViewVideo': typeof import("../components/images/ViewVideo.vue")['default']
    'Layout': typeof import("../components/layout/Layout.vue")['default']
    'LayoutLoadingPage': typeof import("../components/layout/loading/LoadingPage.vue")['default']
    'LayoutLoadingSibling': typeof import("../components/layout/loading/Sibling.vue")['default']
    'LinksLinkAngle': typeof import("../components/links/LinkAngle.vue")['default']
    'LinksLinkCircle': typeof import("../components/links/LinkCircle.vue")['default']
    'LinksLinkCircleArrow': typeof import("../components/links/LinkCircleArrow.vue")['default']
    'LinksLinkDefualt': typeof import("../components/links/LinkDefualt.vue")['default']
    'LinksLinkLine': typeof import("../components/links/LinkLine.vue")['default']
    'LinksLinkNormal': typeof import("../components/links/LinkNormal.vue")['default']
    'LinksLinkScrollDown': typeof import("../components/links/LinkScrollDown.vue")['default']
    'LogoSiteLogo': typeof import("../components/logo/SiteLogo.vue")['default']
    'MenuBlackMenu': typeof import("../components/menu/BlackMenu.vue")['default']
    'MenuContent': typeof import("../components/menu/MenuContent.vue")['default']
    'MenuNavNavbar': typeof import("../components/menu/nav/Navbar.vue")['default']
    'MenuNavContainArrowLeft': typeof import("../components/menu/nav/contain/ArrowLeft.vue")['default']
    'MenuNavContainCollapse': typeof import("../components/menu/nav/contain/Collapse.vue")['default']
    'MenuNavContainDropdown': typeof import("../components/menu/nav/contain/Dropdown.vue")['default']
    'MenuNavContainItemLink': typeof import("../components/menu/nav/contain/ItemLink.vue")['default']
    'MenuNavContainSubLinks': typeof import("../components/menu/nav/contain/SubLinks.vue")['default']
    'MenuNavContainToggle': typeof import("../components/menu/nav/contain/Toggle.vue")['default']
    'MetaPost': typeof import("../components/meta/MetaPost.vue")['default']
    'NextProject': typeof import("../components/next/NextProject.vue")['default']
    'OptionThemeCursorGrowing': typeof import("../components/option-theme/CursorGrowing.vue")['default']
    'OptionThemeModeColors': typeof import("../components/option-theme/ModeColors.vue")['default']
    'OptionThemeRightScrollTop': typeof import("../components/option-theme/RightScrollTop.vue")['default']
    'PortfolioFilter': typeof import("../components/portfolio/PortfolioFilter.vue")['default']
    'PortfolioHorizontalScroll': typeof import("../components/portfolio/PortfolioHorizontalScroll.vue")['default']
    'PortfolioItem': typeof import("../components/portfolio/PortfolioItem.vue")['default']
    'PortfolioSwiper': typeof import("../components/portfolio/PortfolioSwiper.vue")['default']
    'PortfolioImagesSwiper': typeof import("../components/portfolio/images-swiper/ImagesSwiper.vue")['default']
    'PortfolioImagesSwiperItemImage': typeof import("../components/portfolio/images-swiper/ItemImage.vue")['default']
    'PortfolioInfoProject': typeof import("../components/portfolio/info-project/InfoProject.vue")['default']
    'PortfolioInfoProjectItem': typeof import("../components/portfolio/info-project/InfoProjectItem.vue")['default']
    'PortfolioSlider': typeof import("../components/portfolio/slider/PortfolioSlider.vue")['default']
    'PortfolioSliderNext': typeof import("../components/portfolio/slider/SliderNext.vue")['default']
    'PortfolioSliderPrev': typeof import("../components/portfolio/slider/SliderPrev.vue")['default']
    'SectionVideo': typeof import("../components/section-video/SectionVideo.vue")['default']
    'SectionVideoOnly': typeof import("../components/section-video/VideoOnly.vue")['default']
    'SectionsSectionData': typeof import("../components/sections/SectionData.vue")['default']
    'ServicesAboutServices': typeof import("../components/services/AboutServices.vue")['default']
    'ServicesServiceIcon': typeof import("../components/services/ServiceIcon.vue")['default']
    'ServicesServiceStyle': typeof import("../components/services/ServiceStyle.vue")['default']
    'ServicesFour': typeof import("../components/services/ServicesFour.vue")['default']
    'ServicesThree': typeof import("../components/services/ServicesThree.vue")['default']
    'SocialGroup': typeof import("../components/social/SocialGroup.vue")['default']
    'SocialNormal': typeof import("../components/social/SocialNormal.vue")['default']
    'SocialOne': typeof import("../components/social/SocialOne.vue")['default']
    'StringParagraphBox': typeof import("../components/string/ParagraphBox.vue")['default']
    'SvgAnimate': typeof import("../components/svg/SvgAnimate")['default']
    'SvgSeparator': typeof import("../components/svg/SvgSeparator.vue")['default']
    'SwiperPagination': typeof import("../components/swiper-pagination/SwiperPagination.vue")['default']
    'SwiperPaginationOne': typeof import("../components/swiper-pagination/SwiperPaginationOne.vue")['default']
    'Team': typeof import("../components/team/Team.vue")['default']
    'Testimonials': typeof import("../components/testimonials/Testimonials.vue")['default']
    'TitleSectionTitle': typeof import("../components/title/SectionTitle.vue")['default']
    'TitleSectionTitleGrid': typeof import("../components/title/SectionTitleGrid.vue")['default']
    'TitleSectionTitlePin': typeof import("../components/title/SectionTitlePin.vue")['default']
    'ZMainPageBuildVisually': typeof import("../components/z-main-page/BuildVisually.vue")['default']
    'ZMainPageDemosPages': typeof import("../components/z-main-page/DemosPages.vue")['default']
    'ZMainPageHeaderPages': typeof import("../components/z-main-page/HeaderPages.vue")['default']
    'ZMainPagePagesFooter': typeof import("../components/z-main-page/PagesFooter.vue")['default']
    'ZMainPagePortfolioGrids': typeof import("../components/z-main-page/PortfolioGrids.vue")['default']
    'ZMainPagePortfolioSliders': typeof import("../components/z-main-page/PortfolioSliders.vue")['default']
    'ZMainPageTheFeatures': typeof import("../components/z-main-page/TheFeatures.vue")['default']
    'ZMainPageUniqueTitle': typeof import("../components/z-main-page/UniqueTitle.vue")['default']
    'NuxtWelcome': typeof import("../node_modules/nuxt/dist/app/components/welcome")['default']
    'NuxtLayout': typeof import("../node_modules/nuxt/dist/app/components/nuxt-layout")['default']
    'NuxtErrorBoundary': typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default']
    'ClientOnly': typeof import("../node_modules/nuxt/dist/app/components/client-only")['default']
    'DevOnly': typeof import("../node_modules/nuxt/dist/app/components/dev-only")['default']
    'ServerPlaceholder': typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']
    'NuxtLink': typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default']
    'NuxtLoadingIndicator': typeof import("../node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
    'NuxtRouteAnnouncer': typeof import("../node_modules/nuxt/dist/app/components/nuxt-route-announcer")['default']
    'NuxtImg': typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtImg']
    'NuxtPicture': typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtPicture']
    'NuxtPage': typeof import("../node_modules/nuxt/dist/pages/runtime/page")['default']
    'NoScript': typeof import("../node_modules/nuxt/dist/head/runtime/components")['NoScript']
    'Link': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Link']
    'Base': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Base']
    'Title': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Title']
    'Meta': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Meta']
    'Style': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Style']
    'Head': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Head']
    'Html': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Html']
    'Body': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Body']
    'NuxtIsland': typeof import("../node_modules/nuxt/dist/app/components/nuxt-island")['default']
    'NuxtRouteAnnouncer': IslandComponent<typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']>
      'LazyAboutOne': typeof import("../components/about/AboutOne.vue")['default']
    'LazyAboutResume': typeof import("../components/about/AboutResume.vue")['default']
    'LazyBlogList': typeof import("../components/blog/BlogList.vue")['default']
    'LazyBlogOne': typeof import("../components/blog/BlogOne.vue")['default']
    'LazyBlogSwiper': typeof import("../components/blog/BlogSwiper.vue")['default']
    'LazyBlogPostComments': typeof import("../components/blog/PostComments.vue")['default']
    'LazyBlogPostCommentsForm': typeof import("../components/blog/PostCommentsForm.vue")['default']
    'LazyBlogPostData': typeof import("../components/blog/PostData.vue")['default']
    'LazyBlogPostItem': typeof import("../components/blog/PostItem.vue")['default']
    'LazyBlogPostPagination': typeof import("../components/blog/PostPagination.vue")['default']
    'LazyBoxImage': typeof import("../components/box-image/BoxImage.vue")['default']
    'LazyBoxInfo': typeof import("../components/box-info/BoxInfo.vue")['default']
    'LazyBoxInfoFull': typeof import("../components/box-info/BoxInfoFull.vue")['default']
    'LazyBoxInfoItem': typeof import("../components/box-info/BoxInfoItem.vue")['default']
    'LazyBoxInfoList': typeof import("../components/box-info/BoxInfoList.vue")['default']
    'LazyBoxInfoRight': typeof import("../components/box-info/BoxInfoRight.vue")['default']
    'LazyBrand': typeof import("../components/brand/Brand.vue")['default']
    'LazyBrandHorizontal': typeof import("../components/brand/BrandHorizontal.vue")['default']
    'LazyBrandOne': typeof import("../components/brand/BrandOne.vue")['default']
    'LazyBrandTwo': typeof import("../components/brand/BrandTwo.vue")['default']
    'LazyContactForm': typeof import("../components/contact/ContactForm.vue")['default']
    'LazyContactFormSmall': typeof import("../components/contact/ContactFormSmall.vue")['default']
    'LazyContactDsnMap': typeof import("../components/contact/DsnMap.vue")['default']
    'LazyExperienceItem': typeof import("../components/experience/ExperienceItem.vue")['default']
    'LazyExperienceList': typeof import("../components/experience/ExperienceList.vue")['default']
    'LazyFooterDsnFooter': typeof import("../components/footer/DsnFooter.vue")['default']
    'LazyHeaderResume': typeof import("../components/header/HeaderResume.vue")['default']
    'LazyHelperScrollSmooth': typeof import("../components/helper/ScrollSmooth.vue")['default']
    'LazyImagesImagePopup': typeof import("../components/images/ImagePopup.vue")['default']
    'LazyImagesParallaxImage': typeof import("../components/images/ParallaxImage.vue")['default']
    'LazyImagesParallaxImageTwo': typeof import("../components/images/ParallaxImageTwo.vue")['default']
    'LazyImagesScrollImages': typeof import("../components/images/ScrollImages.vue")['default']
    'LazyImagesViewVideo': typeof import("../components/images/ViewVideo.vue")['default']
    'LazyLayout': typeof import("../components/layout/Layout.vue")['default']
    'LazyLayoutLoadingPage': typeof import("../components/layout/loading/LoadingPage.vue")['default']
    'LazyLayoutLoadingSibling': typeof import("../components/layout/loading/Sibling.vue")['default']
    'LazyLinksLinkAngle': typeof import("../components/links/LinkAngle.vue")['default']
    'LazyLinksLinkCircle': typeof import("../components/links/LinkCircle.vue")['default']
    'LazyLinksLinkCircleArrow': typeof import("../components/links/LinkCircleArrow.vue")['default']
    'LazyLinksLinkDefualt': typeof import("../components/links/LinkDefualt.vue")['default']
    'LazyLinksLinkLine': typeof import("../components/links/LinkLine.vue")['default']
    'LazyLinksLinkNormal': typeof import("../components/links/LinkNormal.vue")['default']
    'LazyLinksLinkScrollDown': typeof import("../components/links/LinkScrollDown.vue")['default']
    'LazyLogoSiteLogo': typeof import("../components/logo/SiteLogo.vue")['default']
    'LazyMenuBlackMenu': typeof import("../components/menu/BlackMenu.vue")['default']
    'LazyMenuContent': typeof import("../components/menu/MenuContent.vue")['default']
    'LazyMenuNavNavbar': typeof import("../components/menu/nav/Navbar.vue")['default']
    'LazyMenuNavContainArrowLeft': typeof import("../components/menu/nav/contain/ArrowLeft.vue")['default']
    'LazyMenuNavContainCollapse': typeof import("../components/menu/nav/contain/Collapse.vue")['default']
    'LazyMenuNavContainDropdown': typeof import("../components/menu/nav/contain/Dropdown.vue")['default']
    'LazyMenuNavContainItemLink': typeof import("../components/menu/nav/contain/ItemLink.vue")['default']
    'LazyMenuNavContainSubLinks': typeof import("../components/menu/nav/contain/SubLinks.vue")['default']
    'LazyMenuNavContainToggle': typeof import("../components/menu/nav/contain/Toggle.vue")['default']
    'LazyMetaPost': typeof import("../components/meta/MetaPost.vue")['default']
    'LazyNextProject': typeof import("../components/next/NextProject.vue")['default']
    'LazyOptionThemeCursorGrowing': typeof import("../components/option-theme/CursorGrowing.vue")['default']
    'LazyOptionThemeModeColors': typeof import("../components/option-theme/ModeColors.vue")['default']
    'LazyOptionThemeRightScrollTop': typeof import("../components/option-theme/RightScrollTop.vue")['default']
    'LazyPortfolioFilter': typeof import("../components/portfolio/PortfolioFilter.vue")['default']
    'LazyPortfolioHorizontalScroll': typeof import("../components/portfolio/PortfolioHorizontalScroll.vue")['default']
    'LazyPortfolioItem': typeof import("../components/portfolio/PortfolioItem.vue")['default']
    'LazyPortfolioSwiper': typeof import("../components/portfolio/PortfolioSwiper.vue")['default']
    'LazyPortfolioImagesSwiper': typeof import("../components/portfolio/images-swiper/ImagesSwiper.vue")['default']
    'LazyPortfolioImagesSwiperItemImage': typeof import("../components/portfolio/images-swiper/ItemImage.vue")['default']
    'LazyPortfolioInfoProject': typeof import("../components/portfolio/info-project/InfoProject.vue")['default']
    'LazyPortfolioInfoProjectItem': typeof import("../components/portfolio/info-project/InfoProjectItem.vue")['default']
    'LazyPortfolioSlider': typeof import("../components/portfolio/slider/PortfolioSlider.vue")['default']
    'LazyPortfolioSliderNext': typeof import("../components/portfolio/slider/SliderNext.vue")['default']
    'LazyPortfolioSliderPrev': typeof import("../components/portfolio/slider/SliderPrev.vue")['default']
    'LazySectionVideo': typeof import("../components/section-video/SectionVideo.vue")['default']
    'LazySectionVideoOnly': typeof import("../components/section-video/VideoOnly.vue")['default']
    'LazySectionsSectionData': typeof import("../components/sections/SectionData.vue")['default']
    'LazyServicesAboutServices': typeof import("../components/services/AboutServices.vue")['default']
    'LazyServicesServiceIcon': typeof import("../components/services/ServiceIcon.vue")['default']
    'LazyServicesServiceStyle': typeof import("../components/services/ServiceStyle.vue")['default']
    'LazyServicesFour': typeof import("../components/services/ServicesFour.vue")['default']
    'LazyServicesThree': typeof import("../components/services/ServicesThree.vue")['default']
    'LazySocialGroup': typeof import("../components/social/SocialGroup.vue")['default']
    'LazySocialNormal': typeof import("../components/social/SocialNormal.vue")['default']
    'LazySocialOne': typeof import("../components/social/SocialOne.vue")['default']
    'LazyStringParagraphBox': typeof import("../components/string/ParagraphBox.vue")['default']
    'LazySvgAnimate': typeof import("../components/svg/SvgAnimate")['default']
    'LazySvgSeparator': typeof import("../components/svg/SvgSeparator.vue")['default']
    'LazySwiperPagination': typeof import("../components/swiper-pagination/SwiperPagination.vue")['default']
    'LazySwiperPaginationOne': typeof import("../components/swiper-pagination/SwiperPaginationOne.vue")['default']
    'LazyTeam': typeof import("../components/team/Team.vue")['default']
    'LazyTestimonials': typeof import("../components/testimonials/Testimonials.vue")['default']
    'LazyTitleSectionTitle': typeof import("../components/title/SectionTitle.vue")['default']
    'LazyTitleSectionTitleGrid': typeof import("../components/title/SectionTitleGrid.vue")['default']
    'LazyTitleSectionTitlePin': typeof import("../components/title/SectionTitlePin.vue")['default']
    'LazyZMainPageBuildVisually': typeof import("../components/z-main-page/BuildVisually.vue")['default']
    'LazyZMainPageDemosPages': typeof import("../components/z-main-page/DemosPages.vue")['default']
    'LazyZMainPageHeaderPages': typeof import("../components/z-main-page/HeaderPages.vue")['default']
    'LazyZMainPagePagesFooter': typeof import("../components/z-main-page/PagesFooter.vue")['default']
    'LazyZMainPagePortfolioGrids': typeof import("../components/z-main-page/PortfolioGrids.vue")['default']
    'LazyZMainPagePortfolioSliders': typeof import("../components/z-main-page/PortfolioSliders.vue")['default']
    'LazyZMainPageTheFeatures': typeof import("../components/z-main-page/TheFeatures.vue")['default']
    'LazyZMainPageUniqueTitle': typeof import("../components/z-main-page/UniqueTitle.vue")['default']
    'LazyNuxtWelcome': typeof import("../node_modules/nuxt/dist/app/components/welcome")['default']
    'LazyNuxtLayout': typeof import("../node_modules/nuxt/dist/app/components/nuxt-layout")['default']
    'LazyNuxtErrorBoundary': typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default']
    'LazyClientOnly': typeof import("../node_modules/nuxt/dist/app/components/client-only")['default']
    'LazyDevOnly': typeof import("../node_modules/nuxt/dist/app/components/dev-only")['default']
    'LazyServerPlaceholder': typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']
    'LazyNuxtLink': typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default']
    'LazyNuxtLoadingIndicator': typeof import("../node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
    'LazyNuxtRouteAnnouncer': typeof import("../node_modules/nuxt/dist/app/components/nuxt-route-announcer")['default']
    'LazyNuxtImg': typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtImg']
    'LazyNuxtPicture': typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtPicture']
    'LazyNuxtPage': typeof import("../node_modules/nuxt/dist/pages/runtime/page")['default']
    'LazyNoScript': typeof import("../node_modules/nuxt/dist/head/runtime/components")['NoScript']
    'LazyLink': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Link']
    'LazyBase': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Base']
    'LazyTitle': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Title']
    'LazyMeta': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Meta']
    'LazyStyle': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Style']
    'LazyHead': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Head']
    'LazyHtml': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Html']
    'LazyBody': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Body']
    'LazyNuxtIsland': typeof import("../node_modules/nuxt/dist/app/components/nuxt-island")['default']
    'LazyNuxtRouteAnnouncer': IslandComponent<typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']>
}

declare module '@vue/runtime-core' {
  export interface GlobalComponents extends _GlobalComponents { }
}

declare module '@vue/runtime-dom' {
  export interface GlobalComponents extends _GlobalComponents { }
}

declare module 'vue' {
  export interface GlobalComponents extends _GlobalComponents { }
}

export const AboutOne: typeof import("../components/about/AboutOne.vue")['default']
export const AboutResume: typeof import("../components/about/AboutResume.vue")['default']
export const BlogList: typeof import("../components/blog/BlogList.vue")['default']
export const BlogOne: typeof import("../components/blog/BlogOne.vue")['default']
export const BlogSwiper: typeof import("../components/blog/BlogSwiper.vue")['default']
export const BlogPostComments: typeof import("../components/blog/PostComments.vue")['default']
export const BlogPostCommentsForm: typeof import("../components/blog/PostCommentsForm.vue")['default']
export const BlogPostData: typeof import("../components/blog/PostData.vue")['default']
export const BlogPostItem: typeof import("../components/blog/PostItem.vue")['default']
export const BlogPostPagination: typeof import("../components/blog/PostPagination.vue")['default']
export const BoxImage: typeof import("../components/box-image/BoxImage.vue")['default']
export const BoxInfo: typeof import("../components/box-info/BoxInfo.vue")['default']
export const BoxInfoFull: typeof import("../components/box-info/BoxInfoFull.vue")['default']
export const BoxInfoItem: typeof import("../components/box-info/BoxInfoItem.vue")['default']
export const BoxInfoList: typeof import("../components/box-info/BoxInfoList.vue")['default']
export const BoxInfoRight: typeof import("../components/box-info/BoxInfoRight.vue")['default']
export const Brand: typeof import("../components/brand/Brand.vue")['default']
export const BrandHorizontal: typeof import("../components/brand/BrandHorizontal.vue")['default']
export const BrandOne: typeof import("../components/brand/BrandOne.vue")['default']
export const BrandTwo: typeof import("../components/brand/BrandTwo.vue")['default']
export const ContactForm: typeof import("../components/contact/ContactForm.vue")['default']
export const ContactFormSmall: typeof import("../components/contact/ContactFormSmall.vue")['default']
export const ContactDsnMap: typeof import("../components/contact/DsnMap.vue")['default']
export const ExperienceItem: typeof import("../components/experience/ExperienceItem.vue")['default']
export const ExperienceList: typeof import("../components/experience/ExperienceList.vue")['default']
export const FooterDsnFooter: typeof import("../components/footer/DsnFooter.vue")['default']
export const HeaderResume: typeof import("../components/header/HeaderResume.vue")['default']
export const HelperScrollSmooth: typeof import("../components/helper/ScrollSmooth.vue")['default']
export const ImagesImagePopup: typeof import("../components/images/ImagePopup.vue")['default']
export const ImagesParallaxImage: typeof import("../components/images/ParallaxImage.vue")['default']
export const ImagesParallaxImageTwo: typeof import("../components/images/ParallaxImageTwo.vue")['default']
export const ImagesScrollImages: typeof import("../components/images/ScrollImages.vue")['default']
export const ImagesViewVideo: typeof import("../components/images/ViewVideo.vue")['default']
export const Layout: typeof import("../components/layout/Layout.vue")['default']
export const LayoutLoadingPage: typeof import("../components/layout/loading/LoadingPage.vue")['default']
export const LayoutLoadingSibling: typeof import("../components/layout/loading/Sibling.vue")['default']
export const LinksLinkAngle: typeof import("../components/links/LinkAngle.vue")['default']
export const LinksLinkCircle: typeof import("../components/links/LinkCircle.vue")['default']
export const LinksLinkCircleArrow: typeof import("../components/links/LinkCircleArrow.vue")['default']
export const LinksLinkDefualt: typeof import("../components/links/LinkDefualt.vue")['default']
export const LinksLinkLine: typeof import("../components/links/LinkLine.vue")['default']
export const LinksLinkNormal: typeof import("../components/links/LinkNormal.vue")['default']
export const LinksLinkScrollDown: typeof import("../components/links/LinkScrollDown.vue")['default']
export const LogoSiteLogo: typeof import("../components/logo/SiteLogo.vue")['default']
export const MenuBlackMenu: typeof import("../components/menu/BlackMenu.vue")['default']
export const MenuContent: typeof import("../components/menu/MenuContent.vue")['default']
export const MenuNavNavbar: typeof import("../components/menu/nav/Navbar.vue")['default']
export const MenuNavContainArrowLeft: typeof import("../components/menu/nav/contain/ArrowLeft.vue")['default']
export const MenuNavContainCollapse: typeof import("../components/menu/nav/contain/Collapse.vue")['default']
export const MenuNavContainDropdown: typeof import("../components/menu/nav/contain/Dropdown.vue")['default']
export const MenuNavContainItemLink: typeof import("../components/menu/nav/contain/ItemLink.vue")['default']
export const MenuNavContainSubLinks: typeof import("../components/menu/nav/contain/SubLinks.vue")['default']
export const MenuNavContainToggle: typeof import("../components/menu/nav/contain/Toggle.vue")['default']
export const MetaPost: typeof import("../components/meta/MetaPost.vue")['default']
export const NextProject: typeof import("../components/next/NextProject.vue")['default']
export const OptionThemeCursorGrowing: typeof import("../components/option-theme/CursorGrowing.vue")['default']
export const OptionThemeModeColors: typeof import("../components/option-theme/ModeColors.vue")['default']
export const OptionThemeRightScrollTop: typeof import("../components/option-theme/RightScrollTop.vue")['default']
export const PortfolioFilter: typeof import("../components/portfolio/PortfolioFilter.vue")['default']
export const PortfolioHorizontalScroll: typeof import("../components/portfolio/PortfolioHorizontalScroll.vue")['default']
export const PortfolioItem: typeof import("../components/portfolio/PortfolioItem.vue")['default']
export const PortfolioSwiper: typeof import("../components/portfolio/PortfolioSwiper.vue")['default']
export const PortfolioImagesSwiper: typeof import("../components/portfolio/images-swiper/ImagesSwiper.vue")['default']
export const PortfolioImagesSwiperItemImage: typeof import("../components/portfolio/images-swiper/ItemImage.vue")['default']
export const PortfolioInfoProject: typeof import("../components/portfolio/info-project/InfoProject.vue")['default']
export const PortfolioInfoProjectItem: typeof import("../components/portfolio/info-project/InfoProjectItem.vue")['default']
export const PortfolioSlider: typeof import("../components/portfolio/slider/PortfolioSlider.vue")['default']
export const PortfolioSliderNext: typeof import("../components/portfolio/slider/SliderNext.vue")['default']
export const PortfolioSliderPrev: typeof import("../components/portfolio/slider/SliderPrev.vue")['default']
export const SectionVideo: typeof import("../components/section-video/SectionVideo.vue")['default']
export const SectionVideoOnly: typeof import("../components/section-video/VideoOnly.vue")['default']
export const SectionsSectionData: typeof import("../components/sections/SectionData.vue")['default']
export const ServicesAboutServices: typeof import("../components/services/AboutServices.vue")['default']
export const ServicesServiceIcon: typeof import("../components/services/ServiceIcon.vue")['default']
export const ServicesServiceStyle: typeof import("../components/services/ServiceStyle.vue")['default']
export const ServicesFour: typeof import("../components/services/ServicesFour.vue")['default']
export const ServicesThree: typeof import("../components/services/ServicesThree.vue")['default']
export const SocialGroup: typeof import("../components/social/SocialGroup.vue")['default']
export const SocialNormal: typeof import("../components/social/SocialNormal.vue")['default']
export const SocialOne: typeof import("../components/social/SocialOne.vue")['default']
export const StringParagraphBox: typeof import("../components/string/ParagraphBox.vue")['default']
export const SvgAnimate: typeof import("../components/svg/SvgAnimate")['default']
export const SvgSeparator: typeof import("../components/svg/SvgSeparator.vue")['default']
export const SwiperPagination: typeof import("../components/swiper-pagination/SwiperPagination.vue")['default']
export const SwiperPaginationOne: typeof import("../components/swiper-pagination/SwiperPaginationOne.vue")['default']
export const Team: typeof import("../components/team/Team.vue")['default']
export const Testimonials: typeof import("../components/testimonials/Testimonials.vue")['default']
export const TitleSectionTitle: typeof import("../components/title/SectionTitle.vue")['default']
export const TitleSectionTitleGrid: typeof import("../components/title/SectionTitleGrid.vue")['default']
export const TitleSectionTitlePin: typeof import("../components/title/SectionTitlePin.vue")['default']
export const ZMainPageBuildVisually: typeof import("../components/z-main-page/BuildVisually.vue")['default']
export const ZMainPageDemosPages: typeof import("../components/z-main-page/DemosPages.vue")['default']
export const ZMainPageHeaderPages: typeof import("../components/z-main-page/HeaderPages.vue")['default']
export const ZMainPagePagesFooter: typeof import("../components/z-main-page/PagesFooter.vue")['default']
export const ZMainPagePortfolioGrids: typeof import("../components/z-main-page/PortfolioGrids.vue")['default']
export const ZMainPagePortfolioSliders: typeof import("../components/z-main-page/PortfolioSliders.vue")['default']
export const ZMainPageTheFeatures: typeof import("../components/z-main-page/TheFeatures.vue")['default']
export const ZMainPageUniqueTitle: typeof import("../components/z-main-page/UniqueTitle.vue")['default']
export const NuxtWelcome: typeof import("../node_modules/nuxt/dist/app/components/welcome")['default']
export const NuxtLayout: typeof import("../node_modules/nuxt/dist/app/components/nuxt-layout")['default']
export const NuxtErrorBoundary: typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default']
export const ClientOnly: typeof import("../node_modules/nuxt/dist/app/components/client-only")['default']
export const DevOnly: typeof import("../node_modules/nuxt/dist/app/components/dev-only")['default']
export const ServerPlaceholder: typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']
export const NuxtLink: typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default']
export const NuxtLoadingIndicator: typeof import("../node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
export const NuxtRouteAnnouncer: typeof import("../node_modules/nuxt/dist/app/components/nuxt-route-announcer")['default']
export const NuxtImg: typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtImg']
export const NuxtPicture: typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtPicture']
export const NuxtPage: typeof import("../node_modules/nuxt/dist/pages/runtime/page")['default']
export const NoScript: typeof import("../node_modules/nuxt/dist/head/runtime/components")['NoScript']
export const Link: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Link']
export const Base: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Base']
export const Title: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Title']
export const Meta: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Meta']
export const Style: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Style']
export const Head: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Head']
export const Html: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Html']
export const Body: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Body']
export const NuxtIsland: typeof import("../node_modules/nuxt/dist/app/components/nuxt-island")['default']
export const NuxtRouteAnnouncer: IslandComponent<typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']>
export const LazyAboutOne: typeof import("../components/about/AboutOne.vue")['default']
export const LazyAboutResume: typeof import("../components/about/AboutResume.vue")['default']
export const LazyBlogList: typeof import("../components/blog/BlogList.vue")['default']
export const LazyBlogOne: typeof import("../components/blog/BlogOne.vue")['default']
export const LazyBlogSwiper: typeof import("../components/blog/BlogSwiper.vue")['default']
export const LazyBlogPostComments: typeof import("../components/blog/PostComments.vue")['default']
export const LazyBlogPostCommentsForm: typeof import("../components/blog/PostCommentsForm.vue")['default']
export const LazyBlogPostData: typeof import("../components/blog/PostData.vue")['default']
export const LazyBlogPostItem: typeof import("../components/blog/PostItem.vue")['default']
export const LazyBlogPostPagination: typeof import("../components/blog/PostPagination.vue")['default']
export const LazyBoxImage: typeof import("../components/box-image/BoxImage.vue")['default']
export const LazyBoxInfo: typeof import("../components/box-info/BoxInfo.vue")['default']
export const LazyBoxInfoFull: typeof import("../components/box-info/BoxInfoFull.vue")['default']
export const LazyBoxInfoItem: typeof import("../components/box-info/BoxInfoItem.vue")['default']
export const LazyBoxInfoList: typeof import("../components/box-info/BoxInfoList.vue")['default']
export const LazyBoxInfoRight: typeof import("../components/box-info/BoxInfoRight.vue")['default']
export const LazyBrand: typeof import("../components/brand/Brand.vue")['default']
export const LazyBrandHorizontal: typeof import("../components/brand/BrandHorizontal.vue")['default']
export const LazyBrandOne: typeof import("../components/brand/BrandOne.vue")['default']
export const LazyBrandTwo: typeof import("../components/brand/BrandTwo.vue")['default']
export const LazyContactForm: typeof import("../components/contact/ContactForm.vue")['default']
export const LazyContactFormSmall: typeof import("../components/contact/ContactFormSmall.vue")['default']
export const LazyContactDsnMap: typeof import("../components/contact/DsnMap.vue")['default']
export const LazyExperienceItem: typeof import("../components/experience/ExperienceItem.vue")['default']
export const LazyExperienceList: typeof import("../components/experience/ExperienceList.vue")['default']
export const LazyFooterDsnFooter: typeof import("../components/footer/DsnFooter.vue")['default']
export const LazyHeaderResume: typeof import("../components/header/HeaderResume.vue")['default']
export const LazyHelperScrollSmooth: typeof import("../components/helper/ScrollSmooth.vue")['default']
export const LazyImagesImagePopup: typeof import("../components/images/ImagePopup.vue")['default']
export const LazyImagesParallaxImage: typeof import("../components/images/ParallaxImage.vue")['default']
export const LazyImagesParallaxImageTwo: typeof import("../components/images/ParallaxImageTwo.vue")['default']
export const LazyImagesScrollImages: typeof import("../components/images/ScrollImages.vue")['default']
export const LazyImagesViewVideo: typeof import("../components/images/ViewVideo.vue")['default']
export const LazyLayout: typeof import("../components/layout/Layout.vue")['default']
export const LazyLayoutLoadingPage: typeof import("../components/layout/loading/LoadingPage.vue")['default']
export const LazyLayoutLoadingSibling: typeof import("../components/layout/loading/Sibling.vue")['default']
export const LazyLinksLinkAngle: typeof import("../components/links/LinkAngle.vue")['default']
export const LazyLinksLinkCircle: typeof import("../components/links/LinkCircle.vue")['default']
export const LazyLinksLinkCircleArrow: typeof import("../components/links/LinkCircleArrow.vue")['default']
export const LazyLinksLinkDefualt: typeof import("../components/links/LinkDefualt.vue")['default']
export const LazyLinksLinkLine: typeof import("../components/links/LinkLine.vue")['default']
export const LazyLinksLinkNormal: typeof import("../components/links/LinkNormal.vue")['default']
export const LazyLinksLinkScrollDown: typeof import("../components/links/LinkScrollDown.vue")['default']
export const LazyLogoSiteLogo: typeof import("../components/logo/SiteLogo.vue")['default']
export const LazyMenuBlackMenu: typeof import("../components/menu/BlackMenu.vue")['default']
export const LazyMenuContent: typeof import("../components/menu/MenuContent.vue")['default']
export const LazyMenuNavNavbar: typeof import("../components/menu/nav/Navbar.vue")['default']
export const LazyMenuNavContainArrowLeft: typeof import("../components/menu/nav/contain/ArrowLeft.vue")['default']
export const LazyMenuNavContainCollapse: typeof import("../components/menu/nav/contain/Collapse.vue")['default']
export const LazyMenuNavContainDropdown: typeof import("../components/menu/nav/contain/Dropdown.vue")['default']
export const LazyMenuNavContainItemLink: typeof import("../components/menu/nav/contain/ItemLink.vue")['default']
export const LazyMenuNavContainSubLinks: typeof import("../components/menu/nav/contain/SubLinks.vue")['default']
export const LazyMenuNavContainToggle: typeof import("../components/menu/nav/contain/Toggle.vue")['default']
export const LazyMetaPost: typeof import("../components/meta/MetaPost.vue")['default']
export const LazyNextProject: typeof import("../components/next/NextProject.vue")['default']
export const LazyOptionThemeCursorGrowing: typeof import("../components/option-theme/CursorGrowing.vue")['default']
export const LazyOptionThemeModeColors: typeof import("../components/option-theme/ModeColors.vue")['default']
export const LazyOptionThemeRightScrollTop: typeof import("../components/option-theme/RightScrollTop.vue")['default']
export const LazyPortfolioFilter: typeof import("../components/portfolio/PortfolioFilter.vue")['default']
export const LazyPortfolioHorizontalScroll: typeof import("../components/portfolio/PortfolioHorizontalScroll.vue")['default']
export const LazyPortfolioItem: typeof import("../components/portfolio/PortfolioItem.vue")['default']
export const LazyPortfolioSwiper: typeof import("../components/portfolio/PortfolioSwiper.vue")['default']
export const LazyPortfolioImagesSwiper: typeof import("../components/portfolio/images-swiper/ImagesSwiper.vue")['default']
export const LazyPortfolioImagesSwiperItemImage: typeof import("../components/portfolio/images-swiper/ItemImage.vue")['default']
export const LazyPortfolioInfoProject: typeof import("../components/portfolio/info-project/InfoProject.vue")['default']
export const LazyPortfolioInfoProjectItem: typeof import("../components/portfolio/info-project/InfoProjectItem.vue")['default']
export const LazyPortfolioSlider: typeof import("../components/portfolio/slider/PortfolioSlider.vue")['default']
export const LazyPortfolioSliderNext: typeof import("../components/portfolio/slider/SliderNext.vue")['default']
export const LazyPortfolioSliderPrev: typeof import("../components/portfolio/slider/SliderPrev.vue")['default']
export const LazySectionVideo: typeof import("../components/section-video/SectionVideo.vue")['default']
export const LazySectionVideoOnly: typeof import("../components/section-video/VideoOnly.vue")['default']
export const LazySectionsSectionData: typeof import("../components/sections/SectionData.vue")['default']
export const LazyServicesAboutServices: typeof import("../components/services/AboutServices.vue")['default']
export const LazyServicesServiceIcon: typeof import("../components/services/ServiceIcon.vue")['default']
export const LazyServicesServiceStyle: typeof import("../components/services/ServiceStyle.vue")['default']
export const LazyServicesFour: typeof import("../components/services/ServicesFour.vue")['default']
export const LazyServicesThree: typeof import("../components/services/ServicesThree.vue")['default']
export const LazySocialGroup: typeof import("../components/social/SocialGroup.vue")['default']
export const LazySocialNormal: typeof import("../components/social/SocialNormal.vue")['default']
export const LazySocialOne: typeof import("../components/social/SocialOne.vue")['default']
export const LazyStringParagraphBox: typeof import("../components/string/ParagraphBox.vue")['default']
export const LazySvgAnimate: typeof import("../components/svg/SvgAnimate")['default']
export const LazySvgSeparator: typeof import("../components/svg/SvgSeparator.vue")['default']
export const LazySwiperPagination: typeof import("../components/swiper-pagination/SwiperPagination.vue")['default']
export const LazySwiperPaginationOne: typeof import("../components/swiper-pagination/SwiperPaginationOne.vue")['default']
export const LazyTeam: typeof import("../components/team/Team.vue")['default']
export const LazyTestimonials: typeof import("../components/testimonials/Testimonials.vue")['default']
export const LazyTitleSectionTitle: typeof import("../components/title/SectionTitle.vue")['default']
export const LazyTitleSectionTitleGrid: typeof import("../components/title/SectionTitleGrid.vue")['default']
export const LazyTitleSectionTitlePin: typeof import("../components/title/SectionTitlePin.vue")['default']
export const LazyZMainPageBuildVisually: typeof import("../components/z-main-page/BuildVisually.vue")['default']
export const LazyZMainPageDemosPages: typeof import("../components/z-main-page/DemosPages.vue")['default']
export const LazyZMainPageHeaderPages: typeof import("../components/z-main-page/HeaderPages.vue")['default']
export const LazyZMainPagePagesFooter: typeof import("../components/z-main-page/PagesFooter.vue")['default']
export const LazyZMainPagePortfolioGrids: typeof import("../components/z-main-page/PortfolioGrids.vue")['default']
export const LazyZMainPagePortfolioSliders: typeof import("../components/z-main-page/PortfolioSliders.vue")['default']
export const LazyZMainPageTheFeatures: typeof import("../components/z-main-page/TheFeatures.vue")['default']
export const LazyZMainPageUniqueTitle: typeof import("../components/z-main-page/UniqueTitle.vue")['default']
export const LazyNuxtWelcome: typeof import("../node_modules/nuxt/dist/app/components/welcome")['default']
export const LazyNuxtLayout: typeof import("../node_modules/nuxt/dist/app/components/nuxt-layout")['default']
export const LazyNuxtErrorBoundary: typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default']
export const LazyClientOnly: typeof import("../node_modules/nuxt/dist/app/components/client-only")['default']
export const LazyDevOnly: typeof import("../node_modules/nuxt/dist/app/components/dev-only")['default']
export const LazyServerPlaceholder: typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']
export const LazyNuxtLink: typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default']
export const LazyNuxtLoadingIndicator: typeof import("../node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
export const LazyNuxtRouteAnnouncer: typeof import("../node_modules/nuxt/dist/app/components/nuxt-route-announcer")['default']
export const LazyNuxtImg: typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtImg']
export const LazyNuxtPicture: typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtPicture']
export const LazyNuxtPage: typeof import("../node_modules/nuxt/dist/pages/runtime/page")['default']
export const LazyNoScript: typeof import("../node_modules/nuxt/dist/head/runtime/components")['NoScript']
export const LazyLink: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Link']
export const LazyBase: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Base']
export const LazyTitle: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Title']
export const LazyMeta: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Meta']
export const LazyStyle: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Style']
export const LazyHead: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Head']
export const LazyHtml: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Html']
export const LazyBody: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Body']
export const LazyNuxtIsland: typeof import("../node_modules/nuxt/dist/app/components/nuxt-island")['default']
export const LazyNuxtRouteAnnouncer: IslandComponent<typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']>

export const componentNames: string[]
